### ISSUE TITLE
WSL (1) libc issue

### ISSUE THREAD

**Issue by 573** [allvm/allvm-tools#83]
Running `nix-shell '<allvm>' -A allvm-tools -I allvm=https://github.com/allvm/allvm-tools/archive/master.tar.gz` got me
[this error](http://ix.io/2tao)

**Comment by dtzWill** [comment]
Sorry for the trouble, thanks for giving it a go!  I can say I've had this working on WSL previously (!) but I no longer have a windows machine so can't attest that it still works.

Looks like the musl-based bootstrap doesn't work on WSL, try grabbing already built bits from a binary cache -- such as https://allvm.cachix.org .

I just pushed the build closure to the cache in case anything was missing, I ran over the storage limits there (understatement) so some may have been missing.

----

Is sandboxing used for builds on WSL? If not, that may be the issue-- I suspect it's not supported but in particular this seems to be the cause of the build failure:

Logs are in [this gist](https://gist.github.com/dtzWill/df26eccfdc279b7762d54d9eff9a76fa), here's the first 3 hunks of the diff:

```diff
421c421
< Your (shared) C library seems to be in /nix/store/5b7a4ynm23gm375q1fzbsh4sqc806864-bootstrap-tools/bin/../lib/gcc/../../lib/libc.so.
---
> Your (shared) C library seems to be in /lib/libc.so.
426,427c426
< Where is your C library?
< [/nix/store/5b7a4ynm23gm375q1fzbsh4sqc806864-bootstrap-tools/bin/../lib/gcc/../../lib/libc.so]  
---
> Where is your C library? [/lib/libc.so]  
431c430
< 	/nix/store/5b7a4ynm23gm375q1fzbsh4sqc806864-bootstrap-tools/bin/../lib/gcc/../../lib/libc.so
---
> 	/lib/libc.so
```

So perl ('s build system) is trying to use `/lib/libc.so` which is provided by non-nix (presumably from the WSL filesystem) and appears to run into problems as a result.

Unfortunately despite having worked quite a bit on nixpkgs+musl (bootstrapping up the package set and other things) I'm not sure it ever worked on WSL.  I suspect the exposed `/lib/libc.so` is glibc-ish but honestly have no idea.

It may be possible to coerce the build to not pick up the wrong `libc.so` but I don't know what it'd take offhand.  And other builds may need fixes as well, which may end up being a significant amount of work to chase down.  Or not :D.

If you poke at this further and have any questions or want some eyes on issues you encounter please post back!

Apologies for not getting to this sooner!

**Comment by dtzWill** [comment]
It has received significantly less testing, but allvm-tools themselves built against glibc has no known issues and at least passes basic testing.  In case this is easier to work with, I created a `glibc` branch that does this by default (and dropped the pandoc-based doc generation since that's fairly heavy and to avoid possible issues building through GHC and such)...

So if you'd like you can try that with:

```console
$ nix-shell '<allvm>' -A allvm-tools -I allvm=https://github.com/allvm/allvm-tools/archive/glibc.tar.gz
```

Note that this command (and the one in your original post) are asking for a shell in which one might build allvm-tools not one that has the tools built.  For the other type you'd want something like `nix run allvm.allvm-tools -I allvm=https://github.com/allvm/allvm-tools/archive/glibc.tar.gz`.  LMK if you have any questions or issues :).

---

Just tested that glibc-built allvm-tools (built as indicated above) work here on various allexe's I have on hand, including my terminal and vim.

Hope this helps!

**Comment by 573** [comment]
With glibc.tar.gz it is working for me.
